- name: Playbook para criação de usuarios
  hosts: all
  vars:
    - server_name: servidor01
    - user_name: analistadevops
    - conf_file: /opt/app/app.conf
  tasks:
    - name: criando o usuario
      become: true
      user:
       name: "{{ user_name }}" 
